### ISSUE TITLE
运行命令出错

### ISSUE THREAD

**Issue by ljzsdut** [naah69/Hugo-Algolia-Chinese-Builder#2]
操作步骤：
1、下载release包，并解压
2、拷贝文件到项目目录：/Users/ljzsdut/mynotes
3、修改配置文件
4、运行如下命令

```
➜  mynotes ./main   
current path:/Users/ljzsdut/mynotes
2020/11/26 09:06:36 Dict files path:  [sdata/dict.txt]
2020/11/26 09:06:36 Load the gse dictionary: "sdata/dict.txt" 
2020/11/26 09:06:38 Gse dictionary loaded finished.
2020-11-26 09:06:39 /Users/naah/software/GOPATH/src/github.com/yanyiwu/gojieba/deps/cppjieba/DictTrie.hpp:103 FATAL exp: [ifs.is_open()] false. open /Users/naah/software/GOPATH/src/github.com/yanyiwu/gojieba/dict/user.dict.utf8 failed
SIGABRT: abort
PC=0x7fff74aa92c6 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x43ea350, 0xc000069e08, 0x448d260)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000069dd8 sp=0xc000069da0 pc=0x400580b
github.com/yanyiwu/gojieba._Cfunc_NewJieba(0x4f003e0, 0x4f00540, 0x4f00590, 0x4f005e0, 0x4f00630, 0x0)
        _cgo_gotypes.go:220 +0x4e fp=0xc000069e08 sp=0xc000069dd8 pc=0x438229e
github.com/yanyiwu/gojieba.NewJieba(0xc000546000, 0x1, 0x1, 0x0)
        /Users/naah/software/GOPATH/src/github.com/yanyiwu/gojieba/jieba.go:37 +0x240 fp=0xc000069f00 sp=0xc000069e08 pc=0x4382820
_/Users/naah/Documents/Hugo/Naah-Blog/Hugo-Algolia-Chinese-Builder/src/utils.init.0()
        /Users/naah/Documents/Hugo/Naah-Blog/Hugo-Algolia-Chinese-Builder/src/utils/Participles.go:26 +0x128 fp=0xc000069f78 sp=0xc000069f00 pc=0x4385ef8
_/Users/naah/Documents/Hugo/Naah-Blog/Hugo-Algolia-Chinese-Builder/src/utils.init()
        <autogenerated>:1 +0x98 fp=0xc000069f88 sp=0xc000069f78 pc=0x4386e18
main.init()
        <autogenerated>:1 +0x4f fp=0xc000069f98 sp=0xc000069f88 pc=0x43ea12f
runtime.main()
        /usr/local/go/src/runtime/proc.go:188 +0x1c8 fp=0xc000069fe0 sp=0xc000069f98 pc=0x402fc38
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000069fe8 sp=0xc000069fe0 pc=0x405a3f1

rax    0x0
rbx    0x524c5c0
rcx    0x7ffeefbfee58
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbfee90
rsp    0x7ffeefbfee58
r8     0xb
r9     0x0
r10    0x0
r11    0x206
r12    0x307
r13    0x5800000
r14    0x6
r15    0x2d
rip    0x7fff74aa92c6
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
```

**Comment by naah69** [comment]
sry，不小心带了绝对目录，等我改下，晚些发出来
